# Generated by Django 3.0.4 on 2020-03-05 14:38

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pib', models.CharField(max_length=225, verbose_name='П.І.Б.')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Контактний номер телефону', max_length=31, verbose_name='Номер телефону')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('date_entry', models.DateField(verbose_name='Дата заїзду')),
                ('date_leave', models.DateField(verbose_name='Дата виїзду')),
                ('quantity', models.IntegerField(verbose_name='Кількість осіб')),
                ('room_type', models.CharField(choices=[('Стандарт', 'Стандарт'), ('Комфорт', 'Комфорт'), ('Комфорт Плюс', 'Комфорт Плюс'), ('Люкс', 'Люкс')], max_length=225, verbose_name='Тип Кімнати')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнери',
            },
        ),
    ]
